# Generated by Django 4.2.14 on 2024-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pfp",
            field=models.ImageField(null=True, upload_to="pfp/"),
        ),
    ]
