# Generated by Django 4.2.14 on 2024-09-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_user_pfp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
