# Generated by Django 4.2.14 on 2024-09-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_customer_alter_order_user_remove_restaurant_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="opening_hours",
            field=models.TimeField(default="8:00"),
        ),
    ]
