# Generated by Django 4.2.14 on 2024-09-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_discount_order_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="logo",
            new_name="image",
        ),
    ]
