# Generated by Django 4.2.14 on 2024-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_rename_logo_restaurant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
